### PR TITLE
Update query for cards to reschedule in sync hook

### PR DESCRIPTION
**Pull request by user1823**
Fix: Don't exclude cards done in filtered deck with rescheduling enabled

### CODE REVIEW

**Comment by user1823** [comment]
A scope for improvement:

If auto_disperse_after_reschedule is enabled, don't exclude `Manual` entries (i.e., remove the condition `ease > 0`).

This will allow the add-on to disperse siblings after the user optimizes the parameters and uses "Reschedule cards on change" on another device.

**Comment by L-M-Sherlock** [comment]
Have you tested it several times?

**Comment by user1823** [comment]
I have tested it a few times. If you want, you can wait for 1-2 days so that I get to test it more.

To clarify, I am talking about the changes already made in this PR. I don't know how to implement the change I proposed in my comment (https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/420#issuecomment-2156035272).

**Comment by L-M-Sherlock** [comment]
> I have tested it a few times. If you want, you can wait for 1-2 days so that I get to test it more.

It would be better if you can test it more.

> I don't know how to implement the change

See my last commit 150b73f. Could you help me test it?

**Comment by user1823** [comment]
> See my last commit. Could you help me test it?

Seems to be working well.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
