### PR TITLE
Feat/Set graph retention rates to 1 if no reviews occured

### PR DESCRIPTION
**Pull request by FSchliephacke**
A simple solution for #404

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
The SQL is hard to read. An alternative method is to add 1 to the denominator and the numerator.

**Comment by user1823** [comment]
Instead of modifying the SQL query, you can probably add a condition just after line 212.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/86199dd990d03f664369fa1c1e828a43430a35bd/stats.py#L212

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/15256529/fsrs4anki-helper.ankiaddon.zip)

This patch may also solve your issue. Could you help me test it?

**Review by user1823 — APPROVED** [review]
LGTM

Before:


After:

**Pull request merged**
