### PR TITLE
Improve layout of Estimated knowledge based on notes stats

### PR DESCRIPTION
**Pull request by filipenanclarez**
Here the PR ... 

I also format the Burden stat since it's not possible to do a 'half review'

#214 

image

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
image

They should be consistent.

**Comment by user1823** [comment]
In addition, the presentation doesn't look nice to me. However, I am not sure how to make it better.

Perhaps, something needs to be changed in the subtitles "Knowledge by cards" and "Knowledge by notes".

**Comment by filipenanclarez** [comment]
> In addition, the presentation doesn't look nice to me. However, I am not sure how to make it better.
> 
> Perhaps, something needs to be changed in the subtitles "Knowledge by cards" and "Knowledge by notes".

What about a table layout? Like this:

@L-M-Sherlock @user1823 

image

**Comment by Expertium** [comment]
I actually prefer the current layout over the table

**Comment by L-M-Sherlock** [comment]
I will merge it when https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/232#issuecomment-1716890956 is solved.

**Comment by filipenanclarez** [comment]
> I will merge it when [#232 (comment)](https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/232#issuecomment-1716890956) is solved.

Okay, I'm still doing some testing. As soon as it is finished I will send the PR update.

**Comment by filipenanclarez** [comment]
> I will merge it when [#232 (comment)](https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/232#issuecomment-1716890956) is solved.

Done

**Comment by Expertium** [comment]
There seems to be an extra space. It's a minor issue, but still
image

**Comment by user1823** [comment]
https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/04a373bd14eab35a0bd2ab56d03f98606ebaaa5d#r127367887

**Comment by filipenanclarez** [comment]
> There seems to be an extra space. It's a minor issue, but still image

Thank your for report ... fixed

image

**Comment by filipenanclarez** [comment]
@user1823 done

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
