### PR TITLE
Feat/update to FSRS4Anki 4.0.0

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by user1823** [comment]
There are several places left where the formula needs to be updated:

For the following lines, I have done the math already. Just replace `math.log(x[6])/math.log(x[5])` with `(math.pow(x[6], -1) - 1)/(math.pow(x[5], -1) - 1)`

For example, line 65 in advance.py should look like:
```py
cards = sorted(cards, key=lambda x: (1-(math.pow(x[6], -1) - 1)/(math.pow(x[5], -1) - 1), -x[2]))
```

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/advance.py#L65-L66
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/postpone.py#L65-L66

For the following lines, please do the changes yourself. They should be easy and broadly the same for all.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/postpone.py#L62
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/advance.py#L62
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/advance.py#L101
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/postpone.py#L105
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/disperse_siblings.py#L58
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/reschedule.py#L128
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/stats.py#L34
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/browser/custom_columns.py#L120
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/c2e2ea880ad2e7c4b9d0bac6c525c8266662713c/browser/custom_search_nodes.py#L109

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12041806/fsrs4anki-helper.zip)

**Comment by user1823** [comment]
Still, there are some issues:
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/5e4a404b7935f233ef14a2f67902769fcbe9fd26/advance.py#L71

This should be changed to:
```py
        safe_cnt = len(list(filter(lambda x: 1-(math.pow(x[6], -1) - 1)/(math.pow(x[5], -1) - 1) < 0.13, cards))) 
```

Also, the following lines were not updated.
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/5e4a404b7935f233ef14a2f67902769fcbe9fd26/postpone.py#L65-L66

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12045592/fsrs4anki-helper.zip)

**Pull request merged**
