### PR TITLE
Feat/recommended steps

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Patch: [fsrs4anki-helper.ankiaddon.zip](https://github.com/user-attachments/files/17988513/fsrs4anki-helper.ankiaddon.zip)

Preview:

image

### CODE REVIEW

**Comment by Expertium** [comment]
Suggestion: if recommended learning steps are <10s, just display "Not needed" or something like that

**Comment by L-M-Sherlock** [comment]
> Also, why does it sometimes suggest one learning step, and sometimes two?

If the 2nd learning step is longer than the cutoff, it will be hidden.

**Comment by user1823** [comment]
> Suggestion: if recommended learning steps are <10s, just display "Not needed" or something like that

Why?

**Review by user1823 — COMMENTED** [review]
Functionally, LGTM.

Just being curious. Why is the code written in JS rather than Python?

**Comment by Expertium** [comment]
> Why?

Because <10s is useless

**Comment by user1823** [comment]
> Because <10s is useless

In that case, instead of suggesting the user to remove the steps completely, shouldn't we suggest them a slightly longer but more reasonable step (e.g., 10s or 15s)?

**Comment by L-M-Sherlock** [comment]
> Just being curious. Why is the code written in JS rather than Python?

It's not written by me. I guess only JS could do such a reactive interaction in this page.

**Pull request merged**
