### PR TITLE
Memory states from SM-2 for incomplete review history

### PR DESCRIPTION
**Pull request by user1823**
Context: https://github.com/open-spaced-repetition/fsrs-rs/issues/63#issuecomment-1735323658

I think that I have added most of the code required to make it work. You will just need to do some final touches so that it can become functional. Specifically, you will need to edit line 391 and maybe minor changes to the other parts.

I hope that editing this PR requires less effort than writing all the code yourself.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12729635/fsrs4anki-helper.zip)

Could you help me test it?

**Comment by user1823** [comment]
It didn't work, i.e., the card didn't get custom data.

For example, this card:

**Comment by L-M-Sherlock** [comment]
Patch: [fsrs4anki-helper.zip](https://github.com/open-spaced-repetition/fsrs4anki-helper/files/12729854/fsrs4anki-helper.zip)

I hope it solve the problem.

**Comment by user1823** [comment]
It seems to work well, though I will test it more.

However, I am slightly curious as to why the interval decreased from 1.04 years to 1.01 years. However, this is not a problem.

image

**Comment by L-M-Sherlock** [comment]
> However, I am slightly curious as to why the interval decreased from 1.04 years to 1.01 years. However, this is not a problem.

It would be due to fuzz.

**Comment by user1823** [comment]
I have tested this and it seems to be working fine. Thanks!

I am attaching some screenshots for future reference (or if you are interested in seeing them).

image
image
image
image

**Comment by user1823** [comment]
Before (left) After (right)
imageimage

Total Count increased by 87 cards. 🚀🚀🚀

**Comment by user1823** [comment]
Before merging this, I advise you to check how this affects cards with the first rating as "Manual". Examples:


Source of images: https://forums.ankiweb.net/t/anki-23-10-beta/34912/18

I can't test this case because I don't have such cards.

**Comment by user1823** [comment]
Also, we should test for the case where first review kind is FILTERED and "reschedule cards based on my answers in this deck" is enabled & disabled respectively.

**Comment by L-M-Sherlock** [comment]
> Also, we should test for the case where first review kind is FILTERED and "reschedule cards based on my answers in this deck" is enabled & disabled (both cases separately).

If you enable "reschedule cards based on my answers in this deck", the review kind is REVIEW instead of FILTERED.

> Before merging this, I advise you to check how this affects cards with the first rating as "Manual". Examples:

The second review is treated as the first learning.

**Comment by user1823** [comment]
> > Also, we should test for the case where first review kind is FILTERED and "reschedule cards based on my answers in this deck" is enabled & disabled (both cases separately).
> 
> If you enable "reschedule cards based on my answers in this deck", the review kind is REVIEW instead of FILTERED.

It doesn't seem to be the case when the card is reviewed before it is due.

image


> > Before merging this, I advise you to check how this affects cards with the first rating as "Manual". Examples:
> 
> The second review is treated as the first learning.

Assuming that this is actually what happens, it looks good to me.

**Comment by L-M-Sherlock** [comment]
> It doesn't seem to be the case when the card is reviewed before it is due.

Weird. I read the doc of Anki, it said that:

    /// Old Anki versions called this "Cram" or "Early", and assigned it when
    /// reviewing cards ahead. It is now only used for filtered decks with
    /// rescheduling disabled.

Source: https://github.com/ankitects/anki/blob/05499297e065b7536e701e105eb613a761b7c135/rslib/src/revlog/mod.rs#L65-L75

I need to ask @dae.

**Comment by dae** [comment]
That comment is wrong - it's also applied when a review card is answered early (eg not using is:due to create the filtered deck)

**Comment by L-M-Sherlock** [comment]
Fine. Could I distinguish these two types of review via ease != 0?

**Comment by dae** [comment]
Yes, I think so - the v2 scheduler didn't write revlog entries when not rescheduling, and v3 uses ease 0 when not rescheduling.

**Pull request merged**
