### PR TITLE
Define mature cards

### PR DESCRIPTION
**Pull request by user1823**
Related: https://github.com/open-spaced-repetition/fsrs4anki/issues/351#issuecomment-1685337405

image

Just replace %(i)d with the actual value from the config. I tried but couldn't figure out how to do it.

### CODE REVIEW

**Comment by user1823** [comment]
@Expertium, does it look fine?

**Review by Expertium — APPROVED** [review]
Looks good

**Comment by L-M-Sherlock** [comment]
image

> I tried but couldn't figure out how to do it.

I implemented it.

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
I plan to release it in the next weekend.

**Pull request merged**
