### PR TITLE
Fix/don't reschedule to the past when today is easy day

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by user1823** [comment]
Why do we need allow_to_past to be `True` in some cases? Shouldn't it always be `False`?

**Comment by L-M-Sherlock** [comment]
> Why do we need `allow_to_past` to be `True` in some cases? Shouldn't it always be `False`?

For example, the user increases the desired retention.

**Comment by user1823** [comment]
But in that case, the following code will make the card due in the past.

https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/4f1d969e691ba2a240cf71d28c552c7662e5e243/schedule/reschedule.py#L91-L93

**Comment by L-M-Sherlock** [comment]
> But in that case, the following code will make the card due in the past.

It's intended. The load balance also tries to balance the backlog and the future workload.

**Comment by user1823** [comment]
I am not saying that those cards should not be scheduled in the past.

I am saying that this code (line 91-93) is enough to ensure that the cards are scheduled in the past when the user increases the desired retention (or updates the parameters). So, you don't need to set `allow_to_past` to True.

**Comment by L-M-Sherlock** [comment]
But it doesn't affect those cards whose fuzz ranges include today.

**Comment by user1823** [comment]
Yes, but what benefit do you get by scheduling a card yesterday (or any other past day) instead of today?

**Comment by L-M-Sherlock** [comment]
It makes the `future due` graph looks smoother because the cards due in yesterday are included in the backlog which is hidden by default.

**Comment by user1823** [comment]
With the current load balancer, the graph will NOT look smooth when there is a backlog.

Reason:
Today's workload includes the backlog but tomorrow's workload doesn't. 
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/4f1d969e691ba2a240cf71d28c552c7662e5e243/schedule/reschedule.py#L134-L138
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/4f1d969e691ba2a240cf71d28c552c7662e5e243/schedule/reschedule.py#L61-L65

So, with the current code, after load balancing, today's due count in the Future Due graph will lesser than tomorrow's because today's due count doesn't include the backlog.

If the cards are scheduled today instead of the past, they will be included in today's due count so the graph will be more smooth.

**Comment by user1823** [comment]
Proof:
In the screenshots below, see how the current code makes the today's due count 0 in the Future Due Graph.

Current code:



My code:

**Comment by L-M-Sherlock** [comment]
OK. I will check the PR tonight.

**Pull request merged**
