### PR TITLE
Doc/Explain about more features of the add-on

### PR DESCRIPTION
**Pull request by user1823**
Fixes https://github.com/open-spaced-repetition/fsrs4anki-helper/issues/243

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
@Expertium, could you help me review this PR?

**Review by Expertium — COMMENTED** [review]
Change this:
"It might have a small effect on responsiveness and power consumption because it needs more number of calculations for each review and causes constant queue rebuilding."
To this:
"It might have a small effect on responsiveness of Anki and introduce lag because FSRS needs to perform more calculations for each review, which causes constant queue rebuilding."

**Comment by user1823** [comment]
Updated

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
Thanks for this contribution. I will update the description in the add-on page tomorrow.

**Pull request merged**
