### PR TITLE
Feat/curated add-ons

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by Luc-Mcgrady** [comment]
Hell yeah! Thank you!

**Comment by aleksejrs** [comment]
What does this mean?

**Comment by L-M-Sherlock** [comment]
> What does this mean? Do you, @L-M-Sherlock, check the changes in those add-ons before they release?

I just recommend my favorite add-ons.

**Comment by aleksejrs** [comment]
"Recommended" would be clearer. "curat*" is after #12000 in the three English frequency lists I have, and "recommend*" before 6000.

**Comment by L-M-Sherlock** [comment]
updated in 405d23cf75181b9e24c2809dd6fb88afe16c8e9c

**Pull request merged**
