### PR TITLE
Burden -> Load & Include buried cards in FSRS stats

### PR DESCRIPTION
**Pull request by user1823**
The word "Burden" is too negative. I have replaced it with a neutral word "Load".

### CODE REVIEW

**Comment by user1823** [comment]
@Expertium, what do you think about it?

**Comment by aleksejrs** [comment]
This introduces a new term for a defined thing:

> Total burden, as defined by Piotr Woźniak here: https://supermemo.guru/wiki/Burden

And uses a word that could be used for something else instead.

**Comment by user1823** [comment]
The current code excludes buried cards from FSRS stats. In the last commit, I have changed it to include them too.

For reference, information about queue is documented here:
https://github.com/ankitects/anki/blob/7784321b90be4ed0b9a7cc157cd88295722cb826/pylib/anki/consts.py#L20

**Comment by user1823** [comment]
> This introduces a new term for a defined thing

Yes, but there is a negative connotation attached with the word "burden". Let us see what Expertium and L-M-Sherlock have to say.

**Comment by L-M-Sherlock** [comment]
I'm OK with that. @Expertium, how about you?

**Comment by aleksejrs** [comment]
A problem with the burden formula is that it does not include the cards currently due/overdue. So a better formula for load could be used. And then the word "Load" will already be used for Burden.

**Comment by Expertium** [comment]
I prefer Burden just because it's how Woz uses the word.
Also, I didn't know that it doesn't include due cards, @L-M-Sherlock can you fix that?

**Comment by user1823** [comment]
> I prefer Burden just because it's how Woz uses the word.

But, I don't think that it is a good reason to reuse that word. FSRS is not meant to be a SuperMemo clone, even though there are several similarities.

By the way, people have been suggesting SuperMemo to change its terminology too. See https://supermemopedia.com/wiki/Do_not_use_the_word_Burden

> Also, I didn't know that it doesn't include due cards

aleksejrs means that if a backlog is present, the burden/load can be smaller than the backlog. However, I think that this doesn't need to be "fixed" because the burden/load is meant to be a measure of the estimated daily review load and the backlog wouldn't exist indefinitely.

**Comment by Expertium** [comment]
> aleksejrs means that if a backlog is present, the burden/load can be smaller than the backlog.

Ah, ok. 

Alright, let's change the name to Daily Load. Daily makes it more clear that it refers to the number of cards per day.

**Comment by user1823** [comment]
> Daily makes it more clear that it refers to the number of cards per day.

I can make that change but isn't it redundant? The load is already expressed in reviews / day.

**Comment by Expertium** [comment]
Never underestimate the user's ability to misunderstand simple things.

**Comment by user1823** [comment]
This PR is ready for final review.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
