### PR TITLE
Fix/user should has one normal day at least when setting easy days

### PR DESCRIPTION
**Pull request by Expertium**
I don't know if this works properly, and there is probably a more efficient way of doing it (with a single loop), but I absolutely will not let this go unfixed. LMSherlock, if you can do better than what I did in this PR - please do so.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
What if the user has 6 reduced days and 1 minimum day? It's equal to 6 normal days and 1 minimum day. Should we warn the user in this case?

**Comment by Expertium** [comment]
Good question. I'd say yes. I think we should allow the user to do that, but display a warning "Your current configuration is equivalent to ..."

**Comment by L-M-Sherlock** [comment]
So the condition is the user should have one normal day at least.

**Comment by Expertium** [comment]
The condition for not showing any warnings? Yes.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Comment by Expertium** [comment]
Yeah, I think that's good. And please do this for the native implementation too, thank you.

**Comment by L-M-Sherlock** [comment]
The solution provided by sonnet doesn't work. I don't know how to implement it in Anki. The reactive frontend framework is confusing me. Please ask for other developer.

**Pull request merged**
