### PR TITLE
Feat/Update from V3 option

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
As requested by @user1823 in #228 

image

Did you want something like this? It shows whenever you update with a V3 scheduler.

### CODE REVIEW

**Comment by user1823** [comment]
Yes, I asked for something like this.

But, the things are slightly more complicated. The config in the v4 scheduler code doesn't contain easy bonus and hard interval. So, these should be removed while updating from v3 to v4.

**Comment by user1823** [comment]
Not directly related, but could you make this preserve the custom scheduling code that is placed above the FSRS scheduler. Some users use additional custom scheduling (for minor things) in addition to the FSRS scheduler.

**Comment by Luc-Mcgrady** [comment]
### Before v3 upgrade
image
### After
image

I hope this doesn't give people the wrong impression that the updater updates their weights to be suitable as well.
Anything else?

**Comment by user1823** [comment]
> It is recommended that you upgrade to the V4 scheduler as the V3 scheduler is no longer getting updated.
> This will require you to re-optimize your decks.

This can be changed to:

> FSRS4Anki Helper has detected that you are using the v3 FSRS scheduler. The v4 FSRS scheduler has been released and the v3 FSRS scheduler is no longer getting updates. So, it is recommended that you upgrade to the v4 FSRS scheduler.
> 
> NOTE: The weights of the v3 FSRS scheduler are incompatible with those of the v4 FSRS scheduler. So, if you choose to upgrade to v4, you must re-optimize your weights using the optimizer and then replace the weights in the scheduler config. Here is the link to the latest optimizer: https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb

image

In my opinion, this warning is not important while updating from v3 to v4 because we have already warned the user in the previous message.

image

When updating from v3 to v4, this screen can also be used to remind the user to re-optimize their weights.

> FSRS scheduler updated from v3 to v4 successfully. Do remember to re-optimize your weights using the optimizer and then replace the weights in the scheduler config.

image

Replace "local" with "installed" (many users won't understand what "local" means).

**Comment by user1823** [comment]
LGTM

**Comment by L-M-Sherlock** [comment]
A problem needs to resolve: the scheduler has two different versions: Q5 and Q6. We need to check the version before we update it.

**Comment by Luc-Mcgrady** [comment]
I can not test that as I don't have QT5 Anki installed but that should work.

**Comment by user1823** [comment]
Another issue (it is becoming too complicated 😅):

If a user is not using all the deck configurations, they will not update the parameters of those configurations, leading to something like this:
https://github.com/open-spaced-repetition/fsrs4anki/issues/458#issuecomment-1715883567

Solution:
When updating from v3 to v4, replace all parameters with the default v4 parameters (but don't change the deck names & request retention). This won't increase the work of the users because the older parameters are not valid anyway.

**Comment by Luc-Mcgrady** [comment]
Like that?!?
(This took me way longer than it feels like it should have)

**Comment by user1823** [comment]
This replaces the requestRetention too, but I advised you not to do so because the user's target retention for the decks would not change when the user upgrades from v3 to v4.

> Your deck param configs will each be replaced with the default until you do this.

Remove this. I have an alternative in mind (see below).

image

When updating from v3 to v4, remove the part that says "Your config will be preserved" because it is only partially true and can be misleading.

image

Change it to:

> FSRS scheduler updated from v3 to v4 successfully.
> 
> The weights of the v3 and the v4 FSRS scheduler are incompatible with each other. So, to avoid errors, the weights have been replaced by the default weights for v4.
> 
> For better results, re-optimize your weights using the optimizer and then manually replace the weights in the scheduler config.


By the way, thanks for working on this. When this gets merged, it would make it much easier for the users to upgrade from v3 to v4.

**Comment by Luc-Mcgrady** [comment]
image

Eyy it doesnt look as cluttered as I thought it would.
> (I figure we shouldn't put the ***full*** re-optimization warning here as we already told them 2 screens ago)

I did (kind of) mean the first one but I must not have edited the comment in time, I'm just worried about hitting people with walls of text.

Glad I could help anyway.

**Comment by user1823** [comment]
LGTM

**Review by user1823 — APPROVED** [review]

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
