### PR TITLE
Fix/filter out manual and cram reviews in true retention & use _revlogLimit()

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
fix: 
- https://github.com/ankitects/anki/issues/3453

### CODE REVIEW

**Comment by user1823** [comment]
I don't know why but this doesn't seem to have any effect.

**Comment by user1823** [comment]
Well, that's because the code for true retention already filters the revlogs with `ease = 0` and I don't have any revlogs with `type = 3 and factor = 0`.

**Comment by L-M-Sherlock** [comment]
> Well, that's because the code for true retention already filters the revlogs with `ease = 0`

The previous version doesn't.

**Comment by user1823** [comment]
> The previous version doesn't.

It does filter them in the following lines:
https://github.com/open-spaced-repetition/fsrs4anki-helper/blob/a459532f73c9772398503491035b7bfbc5f78bdf/stats.py#L389-L392

Anyway, the changes LGTM. They don't solve the issue reported by me, though.

**Comment by L-M-Sherlock** [comment]
> It does filter them in the following lines:

Nope. It just treats them as failed (0). That causes the previous discrepancy.

**Comment by user1823** [comment]
Well, these lines include `ease = 1` and `ease > 1`. So, I don't know how the add-on is counting the revlogs with ease = 0.

I think that the discrepancy is corrected because the latest commit in Anki uses the correct code to remove the crammed cards.

**Comment by L-M-Sherlock** [comment]
Fine. The bug has been fixed. It's a good news.

**Pull request merged**
