### PR TITLE
Feat/Scheduler updater

### PR DESCRIPTION
**Pull request by Luc-Mcgrady**
Allows you to update the scheduler code from within Anki.

image

### Without scheduler:
image

### With updated scheduler:
image

### With out of date scheduler:

image
image
image

Not sure how needed this is with the inbuilt rust on the way but whatever.

### CODE REVIEW

**Comment by Luc-Mcgrady** [comment]
That should do it.

**Comment by user1823** [comment]
If the installed scheduler is v3, we should advise them to re-optimize their parameters (using v4 optimizer) and then provide a solution for them to update their scheduler code to v4.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM. I add timeout to avoid freezing Anki.

**Comment by user1823** [comment]
> If the installed scheduler is v3, we should advise the user to re-optimize their parameters (using v4 optimizer) and then provide a solution for them to update their scheduler code to v4.

@Luc-Mcgrady, can you make another PR to implement this?

**Pull request merged**
